--------------------------------------------------------------------------------
---                      HYPRLAND MODULAR CONFIGURATION                      ---
--------------------------------------------------------------------------------
--
-- This configuration follows SOLID principles for better maintainability:
--
-- - Single Responsibility: Each module handles one aspect of configuration
-- - Open/Closed: Easy to extend without modifying existing files
-- - Liskov Substitution: Similar configs follow same patterns
-- - Interface Segregation: Load only what you need
-- - Dependency Inversion: Main config depends on abstractions (modules)
--
-- Structure:
--   conf/       - Core configuration (input, appearance, etc.)
--   keybinds/   - Keybinding modules (base, applications, workspaces, etc.)
--   rules/      - Window and layer rules
--   colors/     - Theme colors
--
-- Monitors and workspace-to-output rules are owned by hyprmoncfg.
-- Generated rules load last via dofile below.
--
--------------------------------------------------------------------------------

-- Make ~/.config/hypr/ requireable so `require("conf.environment")` resolves
-- to ~/.config/hypr/conf/environment.lua, etc.
local hypr_root = os.getenv("HOME") .. "/.config/hypr"
package.path = hypr_root .. "/?.lua;"
            .. hypr_root .. "/?/init.lua;"
            .. package.path

-- Colors & theming (generated by matugen). Exposed as a global so every
-- sub-module can read colors.primary, colors.surface, etc.
_G.colors = require("colors.matugen")

-- Core configuration
require("conf.environment")
require("conf.programs")
require("conf.autostart")
require("conf.input")
require("conf.appearance")
require("conf.layouts")

-- Keybindings
require("keybinds.base")
require("keybinds.applications")
require("keybinds.window-mgmt")
require("keybinds.workspaces")
require("keybinds.submaps")

-- Rules
require("rules.layer-rules")
require("rules.window-rules")

-- hyprmoncfg: generated monitor rules load last so they win over anything above.
-- Keep this exact include; `hyprmoncfg manage`/`doctor` look for it, and
-- `chezmoi apply` must not strip it.
dofile(os.getenv("HOME") .. "/.config/hypr/hyprmoncfg-monitors.lua")
