[tools]
atuin = "18.19.0"
aws-cli = { version = "2.34.32", symlink_bins = "true" }
bat = "0.26.1"
black = "26.5.1"
btop = "1.4.7"
bun = "1.4.0"
chezmoi = "2.72.0"
claude-code = "2.1.241"
cloud-sql-proxy = "2.25.3"
eza = "0.23.5"
fastfetch = "2.67.1"
fd = "10.4.2"
fzf = "0.74.3"
gcloud = "581.0.0"
ghq = "1.10.1"
git-filter-repo = "2.47.0"
"github:facebook/pyrefly" = "1.2.0"
"github:sinelaw/fresh" = "0.4.10"
"github:steveyegge/beads" = { version = "1.2.2", exe = "bd" }
go = "1.27.0"
grok = { version = "1.0.5", bin = "grok", platforms = { windows-arm64 = { bin = "grok.exe", url = "https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-windows-aarch64.exe" }, windows-x64 = { bin = "grok.exe", url = "https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-windows-x86_64.exe" } }, url = 'https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-{{ os() }}-{{ arch(arm64="aarch64", x64="x86_64") }}', version_list_url = "https://x.ai/cli/stable" }
herdr = "0.8.2"
hugo-extended = "0.165.0"
jq = "1.8.2"
lazydocker = "0.25.2"
lazygit = "0.64.1"
neovim = "0.12.5"
node = "26.7.0"
opencode = "1.18.21"
poetry = "2.4.1"
pre-commit = "4.6.2"
python = "3.14.7"
starship = "1.26.0"
television = "0.15.9"
uv = "0.12.3"
yazi = "26.8.15"
zellij = "0.45.0"
zoxide = "0.10.0"
