---
galaxy_info:
  role_name: kanata
  author: Manas Sambare
  description: Configure the Kanata keyboard remapper on Linux hosts.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Archlinux
  galaxy_tags:
    - keyboard
    - kanata

dependencies: []
