---
# Universal defaults. Keep this minimal and cross-platform.

# Chezmoi defaults. Host vars override per machine.
chezmoi_source_repo: "https://github.com/Manas73/dotfiles.git"
chezmoi_source_path: "{{ ansible_user_dir }}/.local/share/chezmoi"
chezmoi_config_path: "{{ ansible_user_dir }}/.config/chezmoi/chezmoi.toml"
chezmoi_age_identity: "{{ ansible_user_dir }}/.config/chezmoi/key.txt"
chezmoi_age_recipient: "age1egva8dwupvqgh2r3d48j2jsrjkfrgvvpjk83vttdcjftlyze5cgs7ccffj"

# Feature enablement defaults. Host vars override.
docker_enabled: false
kanata_enabled: false
gaming_enabled: false
