-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BNQ BenQ EX3210R ETJ8M01783SL0",
  mode = "2560x1440@165.00",
  position = "2560x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:BNQ BenQ EX3210R ETJ8M01786SL0",
  mode = "2560x1440@165.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:BNQ BenQ EX3210R ETJ8M01783SL0", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:BNQ BenQ EX3210R ETJ8M01783SL0" })
hl.workspace_rule({ workspace = "3", monitor = "desc:BNQ BenQ EX3210R ETJ8M01783SL0" })
hl.workspace_rule({ workspace = "4", monitor = "desc:BNQ BenQ EX3210R ETJ8M01783SL0" })
hl.workspace_rule({ workspace = "5", monitor = "desc:BNQ BenQ EX3210R ETJ8M01783SL0" })
hl.workspace_rule({ workspace = "6", monitor = "desc:BNQ BenQ EX3210R ETJ8M01786SL0", default = true, persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "desc:BNQ BenQ EX3210R ETJ8M01786SL0" })
hl.workspace_rule({ workspace = "8", monitor = "desc:BNQ BenQ EX3210R ETJ8M01786SL0" })
hl.workspace_rule({ workspace = "9", monitor = "desc:BNQ BenQ EX3210R ETJ8M01786SL0" })
hl.workspace_rule({ workspace = "10", monitor = "desc:BNQ BenQ EX3210R ETJ8M01786SL0" })
