---
galaxy_info:
  role_name: development
  author: Manas Sambare
  description: Install development tooling across supported platforms.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Archlinux
    - name: MacOSX
  galaxy_tags:
    - development

dependencies: []
