---
- name: Restart Dock
  ansible.builtin.command: killall Dock
  failed_when: false
  changed_when: true

- name: Restart Finder
  ansible.builtin.command: killall Finder
  failed_when: false
  changed_when: true

- name: Restart SystemUIServer
  ansible.builtin.command: killall SystemUIServer
  failed_when: false
  changed_when: true
