---
galaxy_info:
  role_name: gaming
  author: Manas Sambare
  description: Install optional gaming packages.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Archlinux
  galaxy_tags:
    - gaming

dependencies: []
