aur:
  - 1password
  - datagrip
  - datagrip-jre
  - dropbox
  - gitkraken
  - google-chrome
  - kanata-bin
  - matugen-bin
  - onlyoffice-bin
  - pacseek
  - postman-bin
  - pycharm-professional
  - python-screeninfo
  - rambox-pro-bin
  - slack-desktop
  - sublime-text-4
  - ttf-material-design-icons-git
  - ttf-material-icons-git
  - ttf-ms-fonts
  - ttf-vista-fonts
  - webstorm
  - webstorm-jre
  - zoom
core:
  - gnupg
  - psmisc
  - python
  - python-gpgme
extra:
  - alacritty
  - atuin
  - bat
  - btop
  - chezmoi
  - docker
  - docker-buildx
  - docker-compose
  - dolphin
  - dolphin-plugins
  - eza
  - fastfetch
  - firefox
  - fish
  - flameshot
  - fzf
  - ghq
  - git
  - gparted
  - gwenview
  - jq
  - kitty
  - lazygit
  - libadwaita
  - libreoffice-fresh
  - libnotify
  - networkmanager
  - network-manager-applet
  - nm-connection-editor
  - neovim
  - playerctl
  - python-pip
  - python-virtualenv
  - starship
  - ttf-dejavu
  - ttf-droid
  - ttf-fira-code
  - ttf-fira-sans
  - ttf-firacode-nerd
  - ttf-jetbrains-mono-nerd
  - ttf-nerd-fonts-symbols
  - ttf-nerd-fonts-symbols-common
  - ttf-noto-nerd
  - uv
  - vivaldi
  - vivaldi-ffmpeg-codecs
  - vlc
  - xclip
  - xdg-desktop-portal-gtk
  - xorg-xev
  - yazi
  - zellij
  - zoxide
multilib: []
