aur:
  - 1password
  - datagrip
  - datagrip-jre
  - dropbox
  - gitkraken
  - kanata-bin
  - onlyoffice-bin
  - postman-bin
  - pycharm-professional
  - rambox-pro-bin
  - slack-desktop
  - sublime-text-4
  - ttf-ms-fonts
  - ttf-vista-fonts
  - zoom
core:
  - gnupg
  - psmisc
  - python
  - python-gpgme
extra:
  - alacritty
  - atuin
  - bat
  - btop
  - chezmoi
  - docker
  - docker-buildx
  - docker-compose
  - dolphin
  - dolphin-plugins
  - eza
  - fish
  - firefox
  - flameshot
  - fzf
  - ghq
  - git
  - gparted
  - kitty
  - lazygit
  - libreoffice-fresh
  - neovim
  - python-pip
  - python-virtualenv
  - starship
  - ttf-droid
  - ttf-jetbrains-mono-nerd
  - ttf-nerd-fonts-symbols
  - ttf-nerd-fonts-symbols-common
  - ttf-noto-nerd
  - uv
  - vivaldi
  - vivaldi-ffmpeg-codecs
  - vlc
  - yazi
  - zellij
  - zoxide
multilib: []
