---
galaxy_info:
  role_name: arch_packages
  author: Manas Sambare
  description: Install native pacman packages on Arch/Garuda hosts.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Archlinux
  galaxy_tags:
    - packages
    - arch

dependencies: []
